version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    image: finders-service
    container_name: finders-service
    restart: alway
  proxy:
    image: nginx:apline
    restart: alway
    volumes:
      - ./proxy/.config:/etc/nginx/conf.d/default.conf
    ports:
      - "3002:3002"
    depends_on:
      - api
    